displayName=Death Sound Alerts for Raids
author=skeng
description=Plays a customizable sound alert when your fellow raider dies during the Theatre of Blood. Other raids coming soon
tags=raid,theatre of blood,tob,death,sound,alert
plugins=com.raiddeathalert.RaidDeathAlertPlugin
version=
build=standard